apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "base-helm-chart.releaseFullname" . }}
  labels:
    {{- include "base-helm-chart.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configmap }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
