apiVersion: v1
kind: Service
metadata:
  name: {{ include "base-helm-chart.releaseFullname" . }}
  labels:
    {{- include "base-helm-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.name }}
  selector:
    {{- include "base-helm-chart.selectorLabels" . | nindent 4 }}
